# Generated by Django 5.0.6 on 2024-05-08 17:31

import getRatings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('integer_field', models.IntegerField(validators=[getRatings.models.rateValidator])),
                ('comments', models.TextField(max_length=100)),
            ],
        ),
    ]
