# Generated by Django 5.0.6 on 2024-05-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getRatings', '0002_rename_integer_field_ratings_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='comments',
            field=models.TextField(default='no comment', max_length=100),
        ),
    ]
